blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/orgs/sunpath-dev/discussions
    about: For questions that aren't a bug, feature request, or task, use Discussions instead.
